from abc import ABC, abstractmethod
import pandas as pd

class Factor(ABC):
    @abstractmethod
    def name(self) -> str: ...
    @abstractmethod
    def description(self) -> str: ...
    @abstractmethod
    def category(self) -> str: ...
    @abstractmethod
    def compute(self, bars: pd.DataFrame, params: dict = None) -> pd.DataFrame: ...
